<?php

namespace Swiftmade\LhvConnect\Requests;

use GuzzleHttp\Client;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Cache;
use RuntimeException;
use Illuminate\Support\Str;

abstract class AbstractRequest
{
    /**
     * Unique message identifier generated by requesting party.
     */
    public string $messageId;

    /**
     * Date and time when the message was created.
     */
    protected string $creationDateTime;

    public function __construct()
    {
        $fqcn = explode('\\', get_called_class());

        $this->messageId = Str::random(32);

        $this->creationDateTime = date('Y-m-d\TH:i:sP');
    }

    /**
     * The endpoint to send the request to.
     */
    public abstract function endpoint(): string;

    /**
     * Used to filter the message queue using the Filter-Response-Type
     */
    public abstract function responseType(): string;

    /**
     * Body of the request in XML format.
     */
    public abstract function toXml(): string;
}
